=== LucijaZakarija/Otvoreno_racunarstvo_vjezbe/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://or.fer.unizg.hr/album.json",
  "type": "array",
  "title" : "OR Albumi",
  "description": "Skup glazbenih albuma za otvoreno računarstvo.",
  "items": {
    "type": "object",
    "title": "album",
	"description": "Objekt koji sadrži sve podatke o jednom glazbenom albumu",

    "properties": {
      "albumtitle": {
        "type": "string",
        "title" : "Naziv glazbenog albuma",
	"description" : "Naziv glazbenog albuma."
      },
      "wikipedia": {
        "type": "string",
        "title" : "Wikipedia stranica",
	"description" : "Naziv wikipedia stranice."
      },
      "artist": {
        "type": "string",
        "title" : "Izvođač",
	"description" : "Naziv izvođača."
      },
      "genre": {
        "type": "string",
       "title" : "Žanr",
	"description" : "Glazbeni žanr uobičajena je kategorija koja identificira neka  glazbena djela koja pripadaju zajedničkoj tradiciji ili skupu konvencija."
      },
      "metacritic": {
        "type": "integer",
	"title" : "Metacritic",
        "description" : "Metacritic objedinjuje glazbene, igračke, televizijske i filmske kritike vodećih kritičara te objavjluje ocjenu 0-100."
      },
      "lengthalbum": {
        "type": "string",
	"title" : "Duljina albuma",
        "description" : "Duljina albuma izražena kao hh:mm:ss."
      },
      "released": {
        "type": "string",
	"title" : "Datum izdavanja albuma",
        "description" : "Datum izdavanja albuma izražen kao y-d-m."
      },
      "musiclabel": {
        "type": "string",
	"title" : "Izdavačka kuća",
        "description" : "Ime izdavačke kuće glazbenog albuma."
      },
      "numberofsingles": {
        "type": "integer",
	"title" : "Broj singleova",
        "description" : "Broj pjesama koje su objavljenje samostalno."
      },
      "songs": {
        "type": "array",
	"title" : "Pjesme",
        "description" : "Pjesme koje se nalaze na albumu." ,
        "items": {
          "type": "object",
	  "title" : "Pjesme",
          "description" : "Pjesme koje se nalaze na albumu." ,
          "properties": {
            "song": {
              "type": "string",
	  "title" : "Pjesma",
          "description" : "Ime pjesme"
            },
            "songlength": {
              "type": "string",
	  "title" : "Duljina trajanja pjesme",
          "description" : "Duljina trajanja pjesme izražena u minutama."
            }
          },
          "required": [
            "song",
            "songlength"
          ]
        }
      }
    },
    "required": [
      "albumtitle",
      "wikipedia",
      "artist",
      "genre",
      "metacritic",
      "lengthalbum",
      "released",
      "musiclabel",
      "numberofsingles",
      "songs"
    ]
  }
}

=== LucijaZakarija/Otvoreno_racunarstvo_vjezbe/Album_2.json
[
  {
    "albumtitle": "Whatever People Say I Am, Thats What Im Not",
    "wikipedia": "Whatever_People_Say_I_Am,_That%27s_What_I%27m_Not",
    "artist": "Arctic Monkeys",
    "genre": "Indie rock",
    "metacritic": 82,
    "lengthalbum": "00:40:05",
    "released": "2006-01-23",
    "musiclabel": "Domino",
    "numberofsingles": 2,
    "songs": [
      {
        "song": " The View from the Afternoon",
        "songlength": "00:03:38"
      },
      {
        "song": " I Bet You Look Good on the Dancefloor",
        "songlength": "00:02:53"
      },
      {
        "song": " Fake Tales of San Francisco",
        "songlength": "00:02:57"
      },
      {
        "song": " Dancing Shoes",
        "songlength": "00:02:21"
      },
      {
        "song": " You Probably Couldnt See for the Lights but You Were Staring Straight at Me",
        "songlength": "00:02:10"
      },
      {
        "song": " Still Take You Home",
        "songlength": "00:02:53"
      },
      {
        "song": "Riot Van",
        "songlength": "00:02:14"
      },
      {
        "song": " Red Light Indicates Doors Are Secured",
        "songlength": "00:02:23"
      },
      {
        "song": " Mardy Bum",
        "songlength": "00:02:55"
      },
      {
        "song": " Perhaps Vampires Is a Bit Strong But..",
        "songlength": "00:04:28"
      },
      {
        "song": " When the Sun Goes Down",
        "songlength": "00:03:20"
      },
      {
        "song": " From the Ritz to the Rubble",
        "songlength": "00:03:13"
      },
      {
        "song": " A Certain Romance",
        "songlength": "00:05:31"
      }
    ]
  }
]
